websites:
  admin_users:
    url: http://ip:port/GateAdministrator/
    user: user
    password: pwd
    labels:
      page01:
        bnt_aceptar: "Entar al Sistema"
        url_pagination01: "sort.do?layoutCollection=0&layoutCollectionProperty=&layoutCollectionState="
        url_pagination02: "&pagerPage="
      page02:
        menu_usuarios: "Control de Usuarios"
      page03:
        name_select_menu: "seleccionInicial"
        option_select_menu: "Consulta de Usuarios"
        bnt_entra: "Entra al Sistema"
      page04:
        bnt_cons: "Consultar"
      page05:
        class_table: "txt"
        class_td: "txt"
        class_a: "txt"
